//@ts-nocheck
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import getData from "../data/binance";
import { useEffect, useState } from "react";
import { useRouter } from "../node_modules/next/router";
import Tes1 from "../components/tes1"

const Home = () => {
  const [linaBtc, setLinaBtc] = useState(0);
  const [linaUsdt, setLinaUsdt] = useState(null);
  const [btcUsdt, setBtcUsdt] = useState(null);
  const [cosUsdt, setCosUsdt] = useState(null);
  const [cosBtc, setCosBtc] = useState(null);
  const [action, setAction] = useState(false);
  // async function fetchData() {
  //   setInterval(async () => {
  //     const data = await getData();
  //     setLinaBtc(((data.LINAUSDT / data.BTCUSDT) * 100000000).toFixed(2));
  //     setLinaUsdt(data.LINAUSDT);
  //     setBtcUsdt(data.BTCUSDT);

  //     setCosBtc(((data.COSUSDT / data.BTCUSDT) * 100000000).toFixed(2));
  //     setCosUsdt(data.COSUSDT);
  //     //console.log(btcUsdt);
  //   }, 1000 * num);
  // }

  async function fetchData() {
    const data = await getData();
    setLinaBtc(((data.LINAUSDT / data.BTCUSDT) * 100000000).toFixed(2));
    setLinaUsdt(data.LINAUSDT);
    setBtcUsdt(data.BTCUSDT);
    setCosBtc(((data.COSUSDT / data.BTCUSDT) * 100000000).toFixed(2));
    setCosUsdt(data.COSUSDT);
  }

  useEffect(() => {
    const interval = setInterval(() => {
      if (action == "Start" ) fetchData();
      if (action == "Stop" ) {
        setLinaBtc(0);
        setLinaUsdt(0);
        setBtcUsdt(0);
        setCosBtc(0);
        setCosUsdt(0);
      }
    }, 5000);
    return () => clearInterval(interval);
  }, [action]);

  function sendWa() {
    window.open(
      `https://api.whatsapp.com/send?phone=+6289510011398&text=LINA-${linaBtc}%20%7C%7C%20COS-${cosBtc}`
    );
  }

  return (
    <div className="flex flex-col justify-center items-center h-screen">
      <Head>
        <title>Bot trading</title>
        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/bitcoin.png" type="image/x-icon" />
      </Head>

      <table className="shadow-2-xl font-[Poppins] border-2 border-sky-200 w-6/12 overflow-hidden">
        <thead className="text-white">
          <tr>
            <th className="py-3 bg-sky-800">Main Coin</th>
            <th className="py-3 bg-sky-800">Price</th>
            <th className="py-3 bg-sky-800">BaseCoin1</th>
            <th className="py-3 bg-sky-800">BaseCoin2</th>
          </tr>
        </thead>
        <tbody className="text-sky-900 text-left">
          <tr className="bg-sky-200 hover:scale-105 hover:bg-sky-100 cursor-pointer duration-300">
            <td className="py-3 px-6 ">LINABTC</td>
            <td className="py-3 px-6 ">{linaBtc || 0}</td>
            <td className="py-3 px-6 text-xs ">LinaUsdt = {linaUsdt || 0}</td>
            <td className="py-3 px-6 text-xs ">BtcUsdt = {btcUsdt || 0}</td>
          </tr>
          <tr className="bg-sky-200 hover:scale-105 hover:bg-sky-100 cursor-pointer duration-300">
            <td className="py-3 px-6 ">COSBTC</td>
            <td className="py-3 px-6 ">{cosBtc || 0}</td>
            <td className="py-3 px-6 text-xs ">CosUsdt = {cosUsdt || 0}</td>
            <td className="py-3 px-6 text-xs ">BtcUsdt = {btcUsdt || 0}</td>
          </tr>
        </tbody>
      </table>
      <div className="flex gap-2 font-bold">
        <div
          onClick={() => setAction("Start")}
          className="cursor-pointer shadow-[0_7px_#ea580c] active:shadow-none active:relative active:top-[7px] text-white bg-[#fb923c] px-7 py-2 rounded-md"
        >
          <button>Count</button>
        </div>
        <div
          onClick={sendWa}
          className="cursor-pointer shadow-[0_7px_#1a7940] active:shadow-none active:relative active:top-[7px] text-white bg-[#5dca88] px-7 py-2 rounded-md"
        >
          <button>Send</button>
        </div>
        <div
          onClick={() => setAction("Stop")}
          className="cursor-pointer shadow-[0_7px_#b91c1c] active:shadow-none active:relative active:top-[7px] text-white bg-[#f87171] px-7 py-2 rounded-md"
        >
          <button>Stop</button>
        </div>
      </div>
    </div>
  );
};

export default Home;

// <div className=" bg-red-400flex flex-col">
//           <div className="p-3 flex justify-center">
//             <h1 className="font-quicksandp">Base Coin</h1>
//           </div>
//           <div className="flex">
//             <div className="flex gap-2 w-60 p-2 flex  border-r-2 border-slate-500">
//               <p>LINAUSDT</p>
//               <p>=</p>
//               <p className="">{linaUsdt || 0}</p>
//             </div>

//             <div className=" flex gap-2 p-2 w-60 flex ">
//               <p>BTCUSDT</p>
//               <p>=</p>
//               <p className="">{btcUsdt || 0}</p>
//             </div>
//           </div>
//         </div>
//         <div className="flex flex-col">
//           <div className=" p-3">
//             <h1 className="font-quicksand">Main Coin</h1>
//           </div>
//           <div className="p-2">LINABTC</div>
//         </div>

//         <div className="flex flex-col ">
//           <div className=" p-3">
//             <h1 className="font-quicksandp">Current Price</h1>
//           </div>
//           <div className="p-2">{linaBtc || 0.0}</div>
//         </div>
